apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: question1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://chartmuseum.chartmuseum:8080
    targetRevision: '*'
    chart: question1
  destination:
    server: https://kubernetes.default.svc
    namespace: question1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
